# Generated by Django 5.0.6 on 2024-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XlsxReport',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('request_state', models.CharField(max_length=50)),
                ('request_status', models.TextField()),
                ('request_creation_date', models.DateTimeField()),
                ('processing_end_date', models.DateTimeField(blank=True, null=True)),
                ('request_author', models.TextField()),
                ('package_id', models.CharField(max_length=50)),
            ],
        ),
    ]
